In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('../DataSets/Salary_Data.csv')

In [4]:
df

,YearsExperience,Salary
0,1.1,39343.0
1,1.3,46205.0
2,1.5,37731.0
3,2.0,43525.0
4,2.2,39891.0
5,2.9,56642.0
6,3.0,60150.0
7,3.2,54445.0
8,3.2,64445.0
9,3.7,57189.0


In [5]:
df.Salary.unique()

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [6]:
df.Salary.value_counts()

Salary
39343.0     1
46205.0     1
122391.0    1
112635.0    1
116969.0    1
105582.0    1
109431.0    1
113812.0    1
101302.0    1
98273.0     1
91738.0     1
93940.0     1
81363.0     1
83088.0     1
66029.0     1
67938.0     1
61111.0     1
57081.0     1
56957.0     1
55794.0     1
63218.0     1
57189.0     1
64445.0     1
54445.0     1
60150.0     1
56642.0     1
39891.0     1
43525.0     1
37731.0     1
121872.0    1
Name: count, dtype: int64

In [7]:
df.groupby('Salary')['YearsExperience'].sum()

Salary
37731.0      1.5
39343.0      1.1
39891.0      2.2
43525.0      2.0
46205.0      1.3
54445.0      3.2
55794.0      4.0
56642.0      2.9
56957.0      4.0
57081.0      4.1
57189.0      3.7
60150.0      3.0
61111.0      4.5
63218.0      3.9
64445.0      3.2
66029.0      5.1
67938.0      4.9
81363.0      5.9
83088.0      5.3
91738.0      6.8
93940.0      6.0
98273.0      7.1
101302.0     7.9
105582.0     9.0
109431.0     8.7
112635.0     9.6
113812.0     8.2
116969.0     9.5
121872.0    10.5
122391.0    10.3
Name: YearsExperience, dtype: float64

In [8]:
df.groupby('Salary')['YearsExperience'].mean()

Salary
37731.0      1.5
39343.0      1.1
39891.0      2.2
43525.0      2.0
46205.0      1.3
54445.0      3.2
55794.0      4.0
56642.0      2.9
56957.0      4.0
57081.0      4.1
57189.0      3.7
60150.0      3.0
61111.0      4.5
63218.0      3.9
64445.0      3.2
66029.0      5.1
67938.0      4.9
81363.0      5.9
83088.0      5.3
91738.0      6.8
93940.0      6.0
98273.0      7.1
101302.0     7.9
105582.0     9.0
109431.0     8.7
112635.0     9.6
113812.0     8.2
116969.0     9.5
121872.0    10.5
122391.0    10.3
Name: YearsExperience, dtype: float64

In [9]:
pd.crosstab(index=df.Salary,columns=df.YearsExperience,margins=True)

YearsExperience,1.1,1.3,1.5,2.0,2.2,2.9,3.0,3.2,3.7,3.9,...,7.1,7.9,8.2,8.7,9.0,9.5,9.6,10.3,10.5,All
Salary,,,,,,,,,,,,,,,,,,,,,
37731.0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39343.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39891.0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
43525.0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
46205.0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
54445.0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
55794.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
56642.0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
56957.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1


In [10]:
def salary(x):
    if x>=1 and x<=400:
        return 'Mid_n'
    elif x>400 and x<=800:
        return 'early_m'
    elif x>800 and x<=1200:
        return 'morning'
    elif x>1200 and x<=1600:
        return 'afternoon'
    elif x>1600 and x<=2000:
        return 'evening'
    else:
        return 'night'
    

In [11]:
df['Salary']=df.YearsExperience.apply(salary)
df

,YearsExperience,Salary
0,1.1,Mid_n
1,1.3,Mid_n
2,1.5,Mid_n
3,2.0,Mid_n
4,2.2,Mid_n
5,2.9,Mid_n
6,3.0,Mid_n
7,3.2,Mid_n
8,3.2,Mid_n
9,3.7,Mid_n


In [12]:
df['price']=df.YearsExperience.apply(salary)
df

,YearsExperience,Salary,price
0,1.1,Mid_n,Mid_n
1,1.3,Mid_n,Mid_n
2,1.5,Mid_n,Mid_n
3,2.0,Mid_n,Mid_n
4,2.2,Mid_n,Mid_n
5,2.9,Mid_n,Mid_n
6,3.0,Mid_n,Mid_n
7,3.2,Mid_n,Mid_n
8,3.2,Mid_n,Mid_n
9,3.7,Mid_n,Mid_n


In [13]:
df.groupby('Salary')['YearsExperience'].sum()

Salary
Mid_n    159.4
Name: YearsExperience, dtype: float64

In [14]:
df

,YearsExperience,Salary,price
0,1.1,Mid_n,Mid_n
1,1.3,Mid_n,Mid_n
2,1.5,Mid_n,Mid_n
3,2.0,Mid_n,Mid_n
4,2.2,Mid_n,Mid_n
5,2.9,Mid_n,Mid_n
6,3.0,Mid_n,Mid_n
7,3.2,Mid_n,Mid_n
8,3.2,Mid_n,Mid_n
9,3.7,Mid_n,Mid_n


In [15]:
df['year']=df.Salary.str[-2:]
df['month']=df.Salary.str[-6:-2]

In [16]:
df

,YearsExperience,Salary,price,year,month
0,1.1,Mid_n,Mid_n,_n,Mid
1,1.3,Mid_n,Mid_n,_n,Mid
2,1.5,Mid_n,Mid_n,_n,Mid
3,2.0,Mid_n,Mid_n,_n,Mid
4,2.2,Mid_n,Mid_n,_n,Mid
5,2.9,Mid_n,Mid_n,_n,Mid
6,3.0,Mid_n,Mid_n,_n,Mid
7,3.2,Mid_n,Mid_n,_n,Mid
8,3.2,Mid_n,Mid_n,_n,Mid
9,3.7,Mid_n,Mid_n,_n,Mid


In [33]:
a=np.random.rand(6,3,4)

In [34]:
a

array([[[0.91972252, 0.19349816, 0.21830368, 0.23794506],
        [0.75864752, 0.83262286, 0.50533554, 0.61053521],
        [0.70527486, 0.69374039, 0.41154386, 0.88546206]],

       [[0.65506041, 0.96190701, 0.56527077, 0.66745745],
        [0.52299476, 0.5583158 , 0.83295955, 0.17606097],
        [0.32540019, 0.41672825, 0.13751032, 0.84235179]],

       [[0.75105255, 0.87696732, 0.08381073, 0.31207899],
        [0.82990459, 0.63995689, 0.58254257, 0.98342569],
        [0.43467988, 0.78926185, 0.03583743, 0.40241634]],

       [[0.03055376, 0.05670819, 0.13431861, 0.91976119],
        [0.24931705, 0.22000192, 0.45115671, 0.31475083],
        [0.23872874, 0.64294134, 0.41790956, 0.69223362]],

       [[0.3725566 , 0.43639799, 0.0569306 , 0.53874573],
        [0.76233632, 0.20910854, 0.23525822, 0.16243493],
        [0.27089523, 0.76978695, 0.92593949, 0.24729202]],

       [[0.78147626, 0.36300194, 0.19182893, 0.38597859],
        [0.74455961, 0.12010418, 0.46697964, 0.67400266],
    

In [62]:
a=np.random.randint(1,55,size=[4,7,8])

In [63]:
a

array([[[16, 13, 21, 34, 14, 48, 48,  5],
        [ 9, 33, 50, 42, 19,  3, 24, 11],
        [ 7, 13, 36, 18, 38, 52, 44, 14],
        [33, 23, 52, 22, 52, 12, 12, 14],
        [ 1, 32, 35, 10, 46,  3, 31,  7],
        [22, 28, 14, 39, 16, 25, 45, 49],
        [53, 37, 34,  1, 17, 27, 50, 26]],

       [[19,  4, 20, 50, 51, 52, 28, 17],
        [ 1, 36,  4, 54, 14,  6, 40,  7],
        [ 1,  9, 33, 29,  7,  4, 33,  9],
        [54, 31, 40, 39, 25, 20,  1,  9],
        [31, 34, 42, 36, 41, 16, 36, 42],
        [ 3, 15, 44,  7,  4, 18, 30,  4],
        [40, 36, 49, 46, 29,  8, 26, 48]],

       [[12, 32, 33, 42, 37, 10, 34, 50],
        [31, 49,  9,  3, 38, 16, 15, 39],
        [24,  3, 25, 41,  4, 44, 26, 40],
        [49, 21, 28, 34, 48, 52, 24, 11],
        [28, 49, 50, 38,  2, 38, 42, 16],
        [ 5, 51, 38, 38, 15, 40, 20, 40],
        [47, 49, 53, 38,  5, 54, 13, 21]],

       [[36, 27, 46, 16, 18, 14, 29, 21],
        [20, 40, 15, 30,  7, 39, 19, 23],
        [38, 47, 31, 20, 45,

In [64]:
a

array([[[16, 13, 21, 34, 14, 48, 48,  5],
        [ 9, 33, 50, 42, 19,  3, 24, 11],
        [ 7, 13, 36, 18, 38, 52, 44, 14],
        [33, 23, 52, 22, 52, 12, 12, 14],
        [ 1, 32, 35, 10, 46,  3, 31,  7],
        [22, 28, 14, 39, 16, 25, 45, 49],
        [53, 37, 34,  1, 17, 27, 50, 26]],

       [[19,  4, 20, 50, 51, 52, 28, 17],
        [ 1, 36,  4, 54, 14,  6, 40,  7],
        [ 1,  9, 33, 29,  7,  4, 33,  9],
        [54, 31, 40, 39, 25, 20,  1,  9],
        [31, 34, 42, 36, 41, 16, 36, 42],
        [ 3, 15, 44,  7,  4, 18, 30,  4],
        [40, 36, 49, 46, 29,  8, 26, 48]],

       [[12, 32, 33, 42, 37, 10, 34, 50],
        [31, 49,  9,  3, 38, 16, 15, 39],
        [24,  3, 25, 41,  4, 44, 26, 40],
        [49, 21, 28, 34, 48, 52, 24, 11],
        [28, 49, 50, 38,  2, 38, 42, 16],
        [ 5, 51, 38, 38, 15, 40, 20, 40],
        [47, 49, 53, 38,  5, 54, 13, 21]],

       [[36, 27, 46, 16, 18, 14, 29, 21],
        [20, 40, 15, 30,  7, 39, 19, 23],
        [38, 47, 31, 20, 45,

In [65]:
a[1,3,5]

20

In [66]:
a[1,:,2:4]

array([[20, 50],
       [ 4, 54],
       [33, 29],
       [40, 39],
       [42, 36],
       [44,  7],
       [49, 46]])

In [67]:
a[1,2:6]

array([[ 1,  9, 33, 29,  7,  4, 33,  9],
       [54, 31, 40, 39, 25, 20,  1,  9],
       [31, 34, 42, 36, 41, 16, 36, 42],
       [ 3, 15, 44,  7,  4, 18, 30,  4]])